installNamespace: false
controllerReplicas: 1
cniEnabled: true
identity:
  externalCA: true
identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIFJzCCAw+gAwIBAgIUIxaHu8xfpqPc2r4xrTi54s2hRLwwDQYJKoZIhvcNAQEL
  BQAwIzEhMB8GA1UEAwwYbGlua2VyZC10cnVzdC1hbmNob3IuZGV2MB4XDTI1MDky
  NTIyMTM1M1oXDTM1MDkyMzIyMTM1M1owIzEhMB8GA1UEAwwYbGlua2VyZC10cnVz
  dC1hbmNob3IuZGV2MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqJQw
  8AsYiTMtfWmNDGreGVFeQAP3LSWyOp1SyZmNE7/M1k7TPkFGLdWPMxsuQc+e3+8G
  IuPWE1LcNHcTjD2lFV3XcOcuHZGptutIkp5WqTYSI+EF8jgp7tZP9gpqIKFIUIeN
  w75DZ9VKXraU4bRavDIT49G6Z2KiF3Brqra/YaOEQI3dtO1u/awZY1JVZFh6s6Nr
  vDaN4bNSPNIxFHlBJWzlX4yMDnBex7yDqLH2VcaiobIBqASEvTjGRgS493Hj7ggv
  0B/jPom5mX83CsOAf9gWq4nVZWz4yWhOAJAjl/mIWg+lw4sQ7/WJSr+sFyAVdoZB
  immQyUTIJxakEtEvmHdx+NgKK+5bpj4F2xhpF9j9mUsjqovarRZJr/E01nuX0hby
  BnbQoqJv5PcazaDuaeuEe6a8OdrEluygdGXAEyDhEgVPIKYCPJB+ibn/IWazdNt1
  PjzKGLazEc+2o9i9++rwLMmMlGqbjGgmEgRsqRjTm9vzgDXFnzLTvJVr6ToLepcZ
  kNpIhFMeEP0bnEFt1TQdj38LY9Bbbqiv8WM0wzll2P11nfNlET7Ck7fPmRUeqQi7
  3Qjt8pnwmo4BswhWm6rfEXV7MSJzFRo2msOfuT4Ktpmvl2VTSHeqj7fVC6U2dCpO
  tuOPbE1Uwln6j4kuFDuZq7KMkrZ0b7U85GP+YakCAwEAAaNTMFEwHQYDVR0OBBYE
  FHwy8WDZA7t9Lp+bEKE/6VJjZgnGMB8GA1UdIwQYMBaAFHwy8WDZA7t9Lp+bEKE/
  6VJjZgnGMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAIe6E2um
  KuobCpjlEiSetRIvHTYLRRs2njy1QlUcJRAO9oKg5rygE3JUnDNTbyVbI8vnupsA
  0KebPG4aMma38LRqLe0PXysgg2JcXDqPfW+rOiPgv1TkbVtQrHosm23PyAnScOaq
  u8Ty49xvso9XJ3M5RjBws1lQR9odev9V2QEJRmuZ4ndJiztwZhaDiJALZz6/TW1l
  yQ1uM3ArytV4CswBhnOi0geSh/xxk/ulFpwHUcRly4dEYk8LGZQZMNgXeb0Nia1K
  sQ56AF63ASZY3qYqnG27rTgWvQZG9Zp2RumPyIgb57ahDguRp9Q4cJWpgTmz/VJ7
  L9CzypfFiw3EzANaFQYdaKd7z8Od+RS+vXYe54kUGUZUw8wfb+TOUhpwN20K9w07
  lhlitlB1k8mb5N9KGkPMKUeo5vbWK6kLwAQWpvaz/fuaSnNniexcdsLm6t8tMTlm
  E6YJ9nRAyDyMlB+gVKIADh6efzuV5Ox+Y3ug8xsw9Ydwjf0bKNXb236FRkoyFOZ6
  WiofG+qAcARI2xjgxA0eZJWxI/y2Nz6eMh0j9S8FDPyVQSmEfmTlJ0uRHER7JEk4
  ddwQBdJ/8LUkYWvnImtRK339Om9LQ5u24PCmEbZBFbwFdyg0q81nITR6fqG8rnP3
  Z62qPd7rr+EDjyfECmWzIx59uZww33kmrFqu
  -----END CERTIFICATE-----proxy:
  resources:
    requests: { cpu: 20m, memory: 64Mi }
    limits:   { cpu: 200m, memory: 256Mi }
