installNamespace: false
controllerReplicas: 1
proxy:
  resources:
    requests: { cpu: 20m, memory: 64Mi }
    limits:   { cpu: 200m, memory: 256Mi }

identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIFJzCCAw+gAwIBAgIUHWl+r3Mk2Oifdvnxt9JWiimvIFkwDQYJKoZIhvcNAQEL
  BQAwIzEhMB8GA1UEAwwYbGlua2VyZC10cnVzdC1hbmNob3IuZGV2MB4XDTI1MDky
  NTIxMDU0M1oXDTM1MDkyMzIxMDU0M1owIzEhMB8GA1UEAwwYbGlua2VyZC10cnVz
  dC1hbmNob3IuZGV2MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuw95
  Tj6MWrD6XqCXpYT8zIYqZH33jfGlPENipGP5pGUxAna5r9No7WEjiiqlPBwM4wbF
  8N+TcTWJ7Voi9mSqNmXOLxivWJvSWobJ5JSolA/eYNqM//Jn2tT9SgrUCrbGpQ/0
  mszSWY9k1UO09vN1YnGDLsu8mslouYKmjDoZidPdr7fSX/w0SXb3szcZbUoEtn7y
  TWB8TTCAiCcGJArqmNCdwC92usgv96iFz/A681HHwSclHKfRHwDQJmMxQFJ5q64R
  bMSEl0GoSe/ztUWV+anCrUzn3Ah9BoIZ1uiZL8OsrKwflTpkmLkks+WAoQ0hiRw2
  W+JamASr+NN/OfhKC4APSo+wnrB9BleEjEixzONYiE83OOSOTMqHmfZwO4FqCua4
  EZxlcg95MvqglEvK7ZNx/m5QBC8fjj3PaxRJpetRzfODFUknUmmRsW2iRf0wXcXV
  pjGgLGao2Vclnbrl42B6qaODa5+4eqBnVE4giAolmRaMHQpiS2AQ1nO1mDvXAvfK
  LsnoORAOEQuCv1ulxPN+15kciT0xmRZ2uXoI69LzIiKpqu4kH8fHDX10tgIcctQH
  cL4IW8V8G0IsCQB+VQNk+kXzLvsURErtsTgpST2eQ6okQmbnwqovriWWDy/NdZrU
  glTFMjY5M8z5IuUgaqtLcRbehBHnKDuAx3mgqKkCAwEAAaNTMFEwHQYDVR0OBBYE
  FKD4Wq2aYvPAMOPe0LVmmVOLxK32MB8GA1UdIwQYMBaAFKD4Wq2aYvPAMOPe0LVm
  mVOLxK32MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAGg+Uzpu
  4ilQOVSzQMkEXUyI9QCuSIl+1YgoIzQp2Tjnnxiv/NBJJ/fwz696UD/1EyOaVAdU
  k3t9RLkmZ0Y8CKFi+4I3fG5x+kfRIyzPkeOBRcUnz+9KYp0JytfD7JLCQY00gn85
  G64mzZvj+1zQ5d2YAXwUx52G6BITqOOJ1ww7VILFOZ1uTZNeWgElP6x6IhIeJkan
  8blcGnAPFgERd8MT65AptCpoofAadguHy3UB0wz9lzwvlIxFMdQKx+WEYGMpkaq9
  nem/Bl4u2mj5KcjhDjxLdEwOSDYowMSePXbBdapgcpQdFdtTGEYcbewnQANdl5iz
  zXAFLI/fA1y133v7R15dIQOh+/+LV7IreMyQw6HTGDTiyecqGhJnwa6zbemJjBNN
  ARHh91kUTa0LJNbwxI0MAQjt4WfpZj136mghPv1nG6mNmCYGbx7FAn08qDKgGxPr
  ycZS1Yb94xZpOTaXHMVoHFhr2cNFGyvtvIUGe8RV34gCTVj/nH61fbyctU5Kmtqt
  6l4HRwMwAwgLZu2wVzHSUVbwqJa7tTqliripf8Qn4o81DVVky714Dt9ugoVsSe+r
  oTG8wIyneR4Mnaq/P7g/V8/6Ibm2bWbv355BE4R/02x6LqbnAFMZSQq8iTI3j2Ma
  cfz/zuuy2836sCpJHLkxaADQI7q29OTDhVPN
  -----END CERTIFICATE-----
identity:
  issuer:
    scheme: kubernetes.io/tls
    tls:
      crtPEM: |
        -----BEGIN CERTIFICATE-----
        MIIE0DCCArgCFAEL4/mMAKlDP8KNrBt7XGKHVQdvMA0GCSqGSIb3DQEBCwUAMCMx
        ITAfBgNVBAMMGGxpbmtlcmQtdHJ1c3QtYW5jaG9yLmRldjAeFw0yNTA5MjUyMTA1
        NDNaFw0zNTA5MjMyMTA1NDNaMCYxJDAiBgNVBAMMG2xpbmtlcmQtaWRlbnRpdHkt
        aXNzdWVyLmRldjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALeP+IYc
        13hp5atBiB7OwVUeK33oPBr7G5rsAMXTFJCarqk4MuE9GVSbJXbOvqxsYsFgvnCB
        u10kHbofJfE3UDvsk9bavDsaC6plTyEZlWX8Rj/KVw39kpf/IxGvmomEKkNQU/M/
        UATfcFKNRd/9pHjnPSn2zrW7B6ayE+0it40wND1MhqMndj/RVK9Uxv7sfX8hjBE1
        s7xnG9AaAxYqi2LEAVxP63gfErKRhS8nJfgcLgbWQxX+4W47yNfmP+Ypx0j4D6iO
        rigV0yV2OnoCRKZ1pCK1aZ8apn8gkNT/bFDB0AguZf9UUZ3bx9UGMBKL/Z+VJOM/
        xGkiX1h4YrI+QbkETsf//THdLPcvGquNYYQcGEnC+YkUlEQ5bLkZc21b3Y7+q6Hu
        eXZCSNHH+dHu/ZL5loz19uzk4InNbcGHGhd099DW1wfh0ckEJ+9hqjxCrES7CR/g
        VqGFCm/x68XmP58nIYwlMnT034fA9u0vnKiiVeMlhoKg7J7hjjJV5SaBYBQhgvzy
        cNGFZxgcXWB/X8oOHpYZCEWIG8zMYu0kW8k3KcwgsHJR8hSTWaY5cPtRgS1GGgna
        IRF+H8uBuD/zcZQopBNxmCQiDCRHVUkPaSS7ooxBk9TYMuSe2FxNFCs7Z8jKFO8y
        s33qr6UCNdZeO/9JIDZasCF1aeNx0a0jqVyfAgMBAAEwDQYJKoZIhvcNAQELBQAD
        ggIBAHf9e890MqOJjGj1G0ybIzHmI5fKGTy+xoynub32BMex0mbc1JgZDn+I3zeB
        puQ3CPdDdpN0qFHBzK6UHkPzwFxcOXukXezKjpO7IxK5BEGcutq15AQsSuz83tUI
        Yh3xb/OFPKzswoXpYKEodwS/ploQ9owk4RuNkwLaQOT6YXNfZKJIxQKkwMMBcVTh
        rMvX2xtj6AOg8WqC5YdGnJKZFFFxo0oOFEuPicfnOqk4IaeAG1umyYPfQrLXHUyf
        1dpiOvnGWLHUW/HJmV6IKC2LON2vCKJQLqA0uLJG9+xLpwucoWP6OC9UOYyoXUoY
        S4nzMhGI9kswujlPUD1hwcbRoP6hbladh+cJC5UezbvZSBTvQMdCmJ4yXU7jwOpZ
        h09fjVKPewFlnPj891cmqIKpyl1K0U/HjBGq1nchgnAS/pgKQoUG10mAMsN2JVxj
        9RdyhpJI9I+KFgMfF/fNNBuZIDQ4fQLX+hoJlH4CXQlHX4mvroaTrpLdfrnHcnWX
        ebAZo1oqvttC7saoLJAnYyhTlkaxDZnuHald/5Bo06yDIl7VqxsRkF1o0kEwZqS8
        d4gS9MkkNc9qR4ZQizPSmzGE1puga4zID6fEOHrTIBU2pXYZd9nGhV4P1yFR+lpA
        Iy7ZHyQnFYO39op9Yu40oOpspcHSxT1lhVYD5YbOpR51i0DY
        -----END CERTIFICATE-----
      keyPEM: |
        -----BEGIN PRIVATE KEY-----
        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQC3j/iGHNd4aeWr
        QYgezsFVHit96Dwa+xua7ADF0xSQmq6pODLhPRlUmyV2zr6sbGLBYL5wgbtdJB26
        HyXxN1A77JPW2rw7GguqZU8hGZVl/EY/ylcN/ZKX/yMRr5qJhCpDUFPzP1AE33BS
        jUXf/aR45z0p9s61uwemshPtIreNMDQ9TIajJ3Y/0VSvVMb+7H1/IYwRNbO8ZxvQ
        GgMWKotixAFcT+t4HxKykYUvJyX4HC4G1kMV/uFuO8jX5j/mKcdI+A+ojq4oFdMl
        djp6AkSmdaQitWmfGqZ/IJDU/2xQwdAILmX/VFGd28fVBjASi/2flSTjP8RpIl9Y
        eGKyPkG5BE7H//0x3Sz3LxqrjWGEHBhJwvmJFJREOWy5GXNtW92O/quh7nl2QkjR
        x/nR7v2S+ZaM9fbs5OCJzW3BhxoXdPfQ1tcH4dHJBCfvYao8QqxEuwkf4FahhQpv
        8evF5j+fJyGMJTJ09N+HwPbtL5yoolXjJYaCoOye4Y4yVeUmgWAUIYL88nDRhWcY
        HF1gf1/KDh6WGQhFiBvMzGLtJFvJNynMILByUfIUk1mmOXD7UYEtRhoJ2iERfh/L
        gbg/83GUKKQTcZgkIgwkR1VJD2kku6KMQZPU2DLknthcTRQrO2fIyhTvMrN96q+l
        AjXWXjv/SSA2WrAhdWnjcdGtI6lcnwIDAQABAoICAEWIQrLCkBgrvPTfMOnClddh
        Q0ZBRytNPUq05SIKb/rKrSiqghNx6nty/YEAlZeIwuvPcrP5YHjKqnwLOnsh4cGh
        PusfFjgpCIw2LgAyybXFFvMo+UryZ6ot2iHj69z1dHDlJ7e3nt8JqGmM3BAZ60hl
        B3Uy6WBLhX1ubT/ha7gOr2sc5s88rn1EFRkJOwvrlyomEgGe3wOZ5x4wDEVEPmJe
        LsnB+EcbNiDwIIwY/zf5rLGoTecyEkCIYu7tZ/0OjE+mr3/A9FV41u+U1lfLLigD
        3fXL1EORe8oiEtqsGmKI1/2RXc+XKAds7khSPLl5z8u4Wi2+xO6yN32ytGgiTxBa
        3OqdTxvfgyL+ychlJPZiaRR0T8sfLklbdoDpD11HHXduKrtgqCPPA560FaOjzOmr
        C3Dt9nK59/4Z6AszNSojALl+vqOJleYy4vVJWH3le6ex+dAsMJpW9ghvZ+OYyNph
        r6UvlH5JwjT7HI+Sjd8hkPLjH/DLKtYlGkGwsp71IFGsQX6a544V5g3VL9hH53Lf
        IGf3uTAPtVnrixkfeTeEhG9kZ80Tzc835yBzUxtjj3wRkJ4eE2GJex0i06TdHlT8
        cdsFphwhLVKSDw5lEnu8IUr5wt4qI3jNN13yNs7Fu/5C2lAGjILW3AM178D6KctL
        zAXchEyDPA6PuzJ6NWhxAoIBAQDoyAHWdf+2/Z83uvCyp3xBI7l85eZveJ/7jEzN
        cRLXVYj3vaH7O0czEIXQ0F+Khaxyfgb2IQT0f3ehfUbo+3udCDAIC3MMWiCazWqg
        /f33sAj8KwRDWmSp+RKxYRZeHBAaWhyuuBpqLk1Sdem2Qwtc+xXTU805ajqX6qOz
        TREfxFnOJyF+no++HsbS966CqlyTv9JYVV1n0AojVi2yjdIGB9/lZnKpcVqzDxut
        7zNYMLvNL4Z2o3pju5PZtOQdJfMtaeT4S59bvAUVfDcqr+zFc0gDMW5X8dHvkXLI
        oV8yR8ZPhmyIfKTITO21gCgPL4STYsHRNnnK/KLO+TPWZ04HAoIBAQDJ3yzuXrVY
        PXyYkOWBoC7SOfdJ1o1B+6huWGlp+9/BqiQUn2JoKt1C+OvEIjiJXBLJvgjGOlGn
        u5SPWOtw0Hrnl2RXtXAumff+LWvtla2ClTkeqZ4ICdWC8kTZVYQZqOoMpQurYfzC
        mZCBEhQOCXC6YwlrdFNtWZAFsrU5Swt0CIilWWoonObcjhpUoWsqZ5/gxxJJ+75y
        BAhciyMtmKQxH2hUgBdmo9wF0u/TmqBLyDZ5zl/jDre2Lmbtj45b40S4dR8FXjIu
        cNWvftVmnfcp85bAPK3fHqbKn4iOZFRDq3N7M0+J3AEPLO/vSBrAqRNQWOzdRTeZ
        A5Cj5mIAm9apAoIBAQCFCkqCl84ed7WX1G/cq3yIfjJ0/7BD5V0KF5WNlSJ/j5NI
        hEkfnTGELd1NCsqQEPYOOZkg8p4yXuewlDkCzzhG93b8Ig8O8DPSRbS7bm7IMQPx
        m2REWlVOD9xvJF30S3Womffqo631IaFvj5STZp4H9jjzHuIb/mqeiKwmvdUboszw
        1cx+4YCl2FEqIgTLCTL//pHpimBoBK7Go2paslNmvvln0rWVwgNkcy4Oqrddn/y1
        uIPRKn24omxN8OSvBBGH0w3aGt5pP3xoWyXsb7+S2eA+cvHtsXeaxDYmFJSj2AGv
        UdSV7ScAk3cIVMaQZ0gONFMxj0Dskpc6U5Mc5s3hAoIBAAGZQdrVZyw+uGjg5OBk
        61oA2YN9LnsySgAttRAAzaHT/hsns/jNNhlcrUlNWBNGZmOwnJMtTQ49/wwvkRXA
        oOiKm2HSbwP/diZOJ8em4svg8KXchALeSRGTZ5YtBjHJ06ir+e6uhPjpjGppQT1n
        N7xSInX2Yt6/0dMpuiOtA3c0xhhBIAUYUP+4JF89NAMO9QYrrWpmkviGLabF905a
        Ihq9e+8HYKgQbiKhrAKJ+/D9sei/CKVcrXnE3k3NUDxMDXREgS1itJUHkbmlEH2S
        jK2JX01AbcQRkxKRttwh0UUD65MzMdMOqfd7zJ6hfIzACgYd3ipWbP1KOPADWA1X
        LpkCggEAFM1Eo6xSjRzieRV/ON9koC34qN/q+o7N6mp2slmjgWsW9lgwD4XL1Lpj
        5ZgmiVHZPsnZKOKUeyS26A6GhR/ubqVbZlky7qZwMUGq4fAcXKehWOLWVy09n+n9
        fUa+/o45B/BnuVpnSwMg1ztKMZwNDMGsa2XxCXc5TOIoZSXbCp3HSLybtMqxgGML
        pVdHlJgGNWZd+vt79AhZnsXRPWRI0jkQwRq+IipOdd8JQXW7JP/wFJ/HdYFTKpoF
        mxR8QxDptU9C+jcOQE+ppSfKfpvR2lXPp1pWPcXPauRUgld9kPGvSflXGfT31YAf
        UAU2zwo+MGLuTeLusVI9qrXl1S63iw==
        -----END PRIVATE KEY-----
