apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-tools
  namespace: argocd
spec:
  description: Project for platform-level tools (service mesh, monitoring, etc.)
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Platform administrators with full access
      policies:
        - p, proj:platform-tools:admin, applications, *, platform-tools/*, allow
