spec:
  source:
    helm:
      values: |
        proxy:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
        enableHA: false
