spec:
  source:
    helm:
      values: |
        proxy:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        enableHA: true
        controllerReplicas: 3
