apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: 1.16.8
    helm:
      values: |
        installNamespace: false

        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjjCCATSgAwIBAgIRAJBm7WoEomRboDBSK+X8v3QwCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwOTI3MDMw
          OTU2WhcNMzUwOTI1MDMwOTU2WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMA+ZICroChRXBiE
          ICNXC/KiLItp0JQPpKg8gY7Egv3uqY02kXBMtWJ3QNZqOy/ussKSuCfwwdLRLvs9
          kLqhns2jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBQMh8diiVtWEy+A8bANMcq9PguvlzAKBggqhkjOPQQDAgNIADBFAiEA
          rMApeu0o0to8aS3hoGnEaQURTtrdhpWFKTwLyTv57fcCIEjuZFJSbaMqzA5T6z+/
          WUWc2jrPYNozHUJ+4escKbjN
          -----END CERTIFICATE-----

        identity:
          issuer:
            scheme: kubernetes.io/tls
            crtPEM: |
              -----BEGIN CERTIFICATE-----
              MIIBsjCCAVigAwIBAgIQMKO4G/cirlpQT0tFaotKljAKBggqhkjOPQQDAjAlMSMw
              IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNTA5MjcwMzA5
              NTZaFw0zNTA5MjUwMzA5NTZaMCkxJzAlBgNVBAMTHmlkZW50aXR5LmxpbmtlcmQu
              Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ0nnDMrHEmd
              9PKHQZjmqL1SMjJOwbJUAaBlv/O0KkpuoNfv8jgwEZL4u+XL9xeFT7kl95Imdj6P
              xwsjZxEzOMyjZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEA
              MB0GA1UdDgQWBBTfLbkNSHAOWy8LchEK6xYFVBaNlDAfBgNVHSMEGDAWgBQMh8di
              iVtWEy+A8bANMcq9PguvlzAKBggqhkjOPQQDAgNIADBFAiBRrUk5pOSmp95Prcvg
              5e6QCs65TBhiiK+vMHddWDwJfwIhAJyhmhiSzhZGdj/RyiJVGibDGqonEmN3Fc5i
              /n8EXFwU
              -----END CERTIFICATE-----
            keyPEM: |
              -----BEGIN EC PRIVATE KEY-----
              MHcCAQEEIAb/4AqebrPT3j5ze7pN8lcxAgXdkNWSluM6bcygDhv3oAoGCCqGSM49
              AwEHoUQDQgAEnSecMyscSZ308odBmOaovVIyMk7BslQBoGW/87QqSm6g1+/yODAR
              kvi75cv3F4VPuSX3kiZ2Po/HCyNnETM4zA==
              -----END EC PRIVATE KEY-----
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
