apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-tools
  namespace: argocd
spec:
  description: Tools managed by platform engineering
  sourceRepos:
    - https://helm.linkerd.io/stable
    - https://github.com/nolet7/linkered
    - https://bitnami-labs.github.io/sealed-secrets
  destinations:
    - namespace: linkerd
      server: https://kubernetes.default.svc
    - namespace: linkerd-viz
      server: https://kubernetes.default.svc
    - namespace: linkerd-cni
      server: https://kubernetes.default.svc
    - namespace: sealed-secrets
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admins
      description: Platform administrators
      policies:
        - p, proj:platform-tools:admins, applications, *, platform-tools/*, allow

