apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds-dev
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-crds
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
