apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform-tools
    app.kubernetes.io/managed-by: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: "*"
    helm:
      valueFiles:
        - $values/helm-values/dev/control-plane-values.yaml
    # Add your repo so $values works
  sources:
    - repoURL: https://github.com/nolet7/linkered.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"

