apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform-tools
    app.kubernetes.io/managed-by: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://github.com/nolet7/linkered.git   # repo with your manifests/values
    targetRevision: master                           # branch to deploy from
    path: charts/linkerd-control-plane               # chart folder (adjust if needed)
    helm:
      valueFiles:
        - helm-values/dev/control-plane-values.yaml  # trustAnchorsPEM included here
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ApplyOutOfSyncOnly=true

