apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz-dev
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-viz
    targetRevision: "*"
    helm:
      values: |
        installNamespace: false
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
