apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane-dev
  namespace: argocd
spec:
  project: platform-tools
  sources:
    - repoURL: https://github.com/nolet7/linkered
      targetRevision: master
      path: argocd/rbac
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd-control-plane
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/helm-values/dev/control-plane-values.yaml
    - repoURL: https://github.com/nolet7/linkered
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
