# argocd/apps/sealed-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: platform-tools
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: "*"
    helm:
      values: |
        # Install into its own namespace
        namespace: sealed-secrets
        fullnameOverride: sealed-secrets
        secretName: sealed-secrets-key
        serviceAccount:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      # Create the sealed-secrets namespace if it doesn't exist
      - CreateNamespace=true

